/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BrOkiE FF (https://sketchfab.com/mafujarrahaman123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/luna-full-bundle-free-fire-19f3383035dd4b75b58d2006d085ec16
title: Luna Full Bundle_Free Fire
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Modelss(props) {
  const { nodes, materials } = useGLTF('/player.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0031rip_mat0071_0.geometry} material={materials['mat0.071']} />
          </group>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0022rip_mat0080_0.geometry} material={materials['mat0.080']} />
          </group>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0021rip_mat0081_0.geometry} material={materials['mat0.081']} />
          </group>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0020rip_mat0082_0.geometry} material={materials['mat0.082']} />
          </group>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0018rip_mat0084_0.geometry} material={materials['mat0.084']} />
          </group>
          <group rotation={[-1.58, 0, -0.17]} scale={100}>
            <mesh geometry={nodes.Mesh_0014rip_mat0088_0.geometry} material={materials['mat0.088']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/player.gltf')
